### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by cdecinkoKnight** [cleancodelabs/AutoMapper.Contrib.Autofac.DependencyInjection#1]
Once this is installed, how do I configure and use it? Where should I put my maps?

**Comment by alsami** [comment]
Hey @cdecinkoKnight 

Thanks for the feedback.

Let's say you have a console-application. Within that application you have the profiles as well.
One profile would be something like this

```csharp
public class CustomerProfile : Profile 
{
   public CustomerProfile() 
   {
      CreateMap<Customer, CustomerDto>();
   }
}
```

Your `Program.cs` would kind of look like this

```csharp
public static void Main(string[] args)
   {
      var builder = new ContainerBuilder();
      builder.AddAutoMapper(typeof(Program).Assembly); // here you need to pass in one or more assemblies that contain your defined profiles (mappings)
     // more registrations
   }
```

I will add some samples soon. In the meanwhile I hope this helps. You can also take a look at the tests that can be found [here](https://github.com/cleancodelabs/AutoMapper.Contrib.Autofac.DependencyInjection/blob/master/test/AutoMapper.Contrib.Autofac.DependencyInjection.Tests/ContainerBuilderExtensionTests.cs#L15).

**Comment by cdecinkoKnight** [comment]
Thanks.  Looking for an example using it with .NET 4.5+ and Global.asax.

Also, where do you prefer to put your profiles?  Some put them in the main project, some in folder in the Domain project.

**Comment by alsami** [comment]
> Thanks. Looking for an example using it with .NET 4.5+ and Global.asax.

That would be the same given that you are already using `Autofac` as your dependency provider in your ASP.NET applciation. Sadly, this package does only support `.netstandard2.0` therefor you will have to update your project to `net461`

> Also, where do you prefer to put your profiles? Some put them in the main project, some in folder in the Domain project.

I personally wouldn't put them in the domain project. I always create a seperate project for everything related to `AutoMapper` that contains resolvers, profiles and converters. There I reference my presentation-project (dtos) and the project that contain the entities. You can find a sample of mine [here](https://github.com/entertainment-database/Etdb.UserService.AspNetCore).

**Comment by alsami** [comment]
I added some samples in this repository. I hope it gives you an idea about how it works in general. It should be the same for classic ASP.NET given the fact, that you have already registered Autofac as your service provider.
