### ISSUE TITLE
AutoMapper V13 support

### ISSUE THREAD

**Issue by josephwambura** [cleancodelabs/AutoMapper.Contrib.Autofac.DependencyInjection#14]
Upgrade

```
<PackageReference Include="AutoMapper" Version="12.0.1" />
```

to

```
<PackageReference Include="AutoMapper" Version="13.0.1" />
```

**Comment by alsami** [comment]
I did not set a limit on the version. You may just install a newer version on top of this package as long as it works. I will try to update the package in the next days.

**Comment by alsami** [comment]
New version 8.0.0 is now on its way and should be on nuget.org in about 10-15 minutes.
