### ISSUE TITLE
The automatic mapping is faulty

### ISSUE THREAD

**Issue by wz172** [cleancodelabs/AutoMapper.Contrib.Autofac.DependencyInjection#15]
I use autofac to replace the container，This is the injection method
`     builder.RegisterAutoMapper((config) =>
     {
         config.ReplaceMemberName("_", "");
     }, ThisAssembly, true);`

Entity class

  public string? UNIT_STATUS_REMARKS { get; set; }
  public string? REMARKS { get; set; }

Dto
 public string? UnitStatusRemarks { get; set; }

 public string? Remarks { get; set; }

mapping

 CreateMap<SamplePosInfoCreateDto, TB_SAMPLE_POS_INFO>();

When I only assign values to the dto's Remark, UNIT_STATUS_REMARKS mapped entities also have values, and hopefully someone will be able to answer them and give a solution

Thanks

**Comment by alsami** [comment]
Can you provide me a small project so that I can reproduce the issue please? I cannot follow your request, it does not tell me enough to know what may be causing the issue.

**Comment by wz172** [comment]
> Can you provide me a small project so that I can reproduce the issue please? I cannot follow your request, it does not tell me enough to know what may be causing the issue.

I see. It was triggered when my Dto was mapped to an entity attribute
Flat mapping
A common use of object-object mapping is to take a complex object model and flatten it into a simpler model.You can take a complex model
Thank you very much for your answer

**Comment by alsami** [comment]
> > Can you provide me a small project so that I can reproduce the issue please? I cannot follow your request, it does not tell me enough to know what may be causing the issue.
> 
> I see. It was triggered when my Dto was mapped to an entity attribute Flat mapping A common use of object-object mapping is to take a complex object model and flatten it into a simpler model.You can take a complex model Thank you very much for your answer

That does not work with Automapper without extra steps. You can use type converters for that:
https://docs.automapper.org/en/stable/Custom-type-converters.html
