### ISSUE TITLE
Different constructor for adding the profiles?

### ISSUE THREAD

**Issue by dmoonfire** [cleancodelabs/AutoMapper.Contrib.Autofac.DependencyInjection#4]
Salutations.

I was trying to implement a profile that took constructors:

```
public class CustomProfiler : Profiler
{
    public CustomProfiler(ISomething something) {}
}
```

However, it didn't work since it required an empty constructor. Looking at the code, it appears that the culprit is [this line](https://github.com/alsami/AutoMapper.Contrib.Autofac.DependencyInjection/blob/61741ef776120339a589189a5dcb11b286802578/src/AutoMapper.Contrib.Autofac.DependencyInjection/AutoMapperModule.cs#L69).

```
            foreach (var profile in profiles.Select(profile => profile.GetType())) 
                cfg.AddProfile(profile);
```

However, when I looked at the interface above, I saw [this overload on the class](https://github.com/AutoMapper/AutoMapper/blob/daf978fdd9057d1e5849334894aa493d66a7a045/src/AutoMapper/IMapperConfigurationExpression.cs#L15):

```
        /// <summary>
        /// Add an existing profile
        /// </summary>
        /// <param name="profile">Profile to add</param>
        void AddProfile(Profile profile);
```

With that, it looks like the above loop could just be changed to:

```
            foreach (var profile in profiles) 
                cfg.AddProfile(profile);
```

That method was added in 2016, so I'm curious of the reasoning for using the type version instead of the instance. I hacked a local copy and it seems to work, but you may have additional insight I'm missing.

Thank you.

**Comment by alsami** [comment]
Hey, happy new year!

To be honest I oriented myself on the registration used with Microsoft DI for the [official integration](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection) and just translated it.

I think it should be fine to use the other method to register the profiles. Will double check and add required tests and do a release soon!

Cheers

**Comment by alsami** [comment]
Release is on [its way](https://travis-ci.com/github/alsami/AutoMapper.Contrib.Autofac.DependencyInjection/builds/211499576). 

Just out of curiosity, why would you want to have dependencies in profiles?

**Comment by dmoonfire** [comment]
Thank you.

The main reason, which I'm sure probably isn't "best practice", is that I have a set list of users groups (creatively called `UserGroup` with a `UserGroupId` and a bunch of methods that calculate values based on their rank, how much they donate through Patreon, etc). All of that is stored at the user group level because of SRP.

In the database, however, a specific user's entry (`UserGroupUser`) only has the minimum information (`UserId`, `UserGroupId`, `Rank`) because... don't copy data in the database for every field.

The information the user gets is: `UserGroupName`, `RankLabel`, `RankDescription`. All three of those basically are functions into the user group but I need that user group lookup in the mapper otherwise, I have to have a `for` loop every place I call the automapper which defeats much of the purpose of having it "just work".
