### ISSUE TITLE
IValueConverter registering is not supported

### ISSUE THREAD

**Issue by Dylan-mts** [cleancodelabs/AutoMapper.Contrib.Autofac.DependencyInjection#5]
Hello,

It seems that [IValueConverter](https://docs.automapper.org/en/stable/Value-converters.html) implementations are not supported in the AutoMapperModule.
I tried to use an implementation of IValueConverter in my code, thinking that the registration would be done automatically with this great package but I got an error indicating that my implementation was not registered.
Therefore, I used an IValueResolver as a workaround.

Thanks for the great work done.

**Comment by alsami** [comment]
Thanks for the heads up! It's indeed not implemented as you can see [here](https://github.com/alsami/AutoMapper.Contrib.Autofac.DependencyInjection/blob/master/src/AutoMapper.Contrib.Autofac.DependencyInjection/AutoMapperModule.cs#L43).  Looks like a feature of `AutoMapper` that I missed. 

I can add that but only later today or tomorrow. Feel free to add the missing type registration and send a PR if you need it earlier.

Cheers,
Sami

**Comment by alsami** [comment]
[Release 5.3.0](https://travis-ci.com/github/alsami/AutoMapper.Contrib.Autofac.DependencyInjection/builds/219778744) is being built and published right now. Should be on NuGet.org within the next 30 minutes.
